# this is mysql config
[list]
    [list.default]
        driver_name = "mysql"
        data_source_name = "root:root(127.0.0.1:3306)/test?charset=utf8mb4&parseTime=true&loc=Local"
        max_open_conn = 200
        max_idle_conn = 100
        max_conn_life_time = 100